# Comment if not use Vault #######################
spring:
  cloud:
    vault:
      uri: ${VAULT_ADDR}
      authentication: TOKEN
      token: ${VAULT_TOKEN} # Vault Token authentication
      kv:
        enabled: true
        backend: non-prod
        default-context: credentials
  config:
    import: vault://${spring.cloud.vault.kv.backend}/${spring.cloud.vault.kv.default-context}
# Uncomment if not use Vault ############################
#visa:
#  direct:
#    apiKey: HX5OQRQSYA524HPHZ6Y921Bq8T31S5D8Lb7C_Qz0jVRi8UrfM
#    apiSecret: UuN6YzByx19LFBOkpn9yu6G9Jos6lXMlAsAF
#    url-base: https://sandbox.api.visa.com/
#    url-funds: visadirect/fundstransfer/v1/
#    url-reverse-funds: visadirect/v1/
#    url-foreign-exchage: forexrates/v2/
#    url-paai-funds-transf: paai/fundstransferattinq/v5/cardattributes/
#server:
#  ssl:
#    key-store: src/main/resources/trust-cert/53_visa_keyAndCertBundle.p12
#    key-store-password: 12345678
#    key-store-type: PKCS12
#    key-alias: 1
#value:
#  algorithm: SunX509
#  protocol: TLS