spring:
  datasource:
    url: jdbc:h2:file:C:/Users/User/Desktop/db/tap_on_phone_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: false
    enabled: false
values:
  saas-id: 1234

#  cloud:
#    vault:
#      uri: ${VAULT_ADDR}
#      authentication: TOKEN
#      token: ${VAULT_TOKEN} # Vault Token authentication
#      kv:
#        enabled: true
#        backend: non-prod
#        default-context: credentials
#  config:
#    import: vault://${spring.cloud.vault.kv.backend}/${spring.cloud.vault.kv.default-context}